repos:
    # Talisman
    - repo: https://github.com/thoughtworks/talisman
      rev: "v1.29.1"
      hooks:
          - id: talisman-commit
            entry: cmd --githook pre-commit

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-yaml

    # Formatter
    - repo: local
      hooks:
          - id: csharpier
            name: csharpier
            language: system
            types_or: ["c#"]
            entry: dotnet csharpier

    # Linter
    - repo: local
      hooks:
          - id: dotnet-format-style
            name: dotnet format style
            language: system
            types_or: ["c#"]
            entry: dotnet format style --include

    - repo: local
      hooks:
          - id: dotnet-format-analyzers
            name: dotnet format analyzers
            language: system
            types_or: ["c#"]
            entry: dotnet format analyzers --include
