---
repos:
  # Talisman
  - repo: https://github.com/thoughtworks/talisman
    rev: "v1.30.2"
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit

  # Megalinter
  - repo: https://github.com/oxsecurity/megalinter
    rev: v6.22.2
    hooks:
      - id: megalinter-incremental
        stages:
          - commit
        args:
          - mega-linter-runner
          - --flavor
          - "dotnet"
          - --containername
          - "megalinter-incremental"
          - --remove-container
          - --fix
          - --env
          - "'APPLY_FIXES=all'"
          - --env
          - "'CLEAR_REPORT_FOLDER=true'"
          - --env
          - "'LOG_LEVEL=warning'"
          - --filesonly
